import type { SiteDefinition } from "./types";

export const DEFAULT_SITES: SiteDefinition[] = [
  {
    id: "imdb",
    name: "IMDb",
    urlPattern: "*://*.imdb.com/title/*",
    mediaType: "auto",
    badgeSelector: 'h1[data-testid="hero-title-block__title"], h1',
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "justwatch",
    name: "JustWatch",
    urlPattern: "*://*.justwatch.com/*/movie/*, *://*.justwatch.com/*/tv-show/*, *://*.justwatch.com/*/tv-series/*",
    mediaType: "auto",
    badgeSelector: ".title-block h1, h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "letterboxd",
    name: "Letterboxd",
    urlPattern: "*://*.letterboxd.com/film/*",
    mediaType: "movie",
    badgeSelector: ".headline-1, h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "metacritic",
    name: "Metacritic",
    urlPattern: "*://*.metacritic.com/movie/*, *://*.metacritic.com/tv/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "nzbforyou",
    name: "NZBForYou",
    urlPattern: "*://*.nzbforyou.com/viewtopic.php*",
    mediaType: "auto",
    badgeSelector: "h3.first",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "nzbgeek",
    name: "NZBGeek",
    urlPattern: "*://*.nzbgeek.info/geekseek.php*",
    mediaType: "auto",
    badgeSelector: "span.overlay_title",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "plex-app",
    name: "Plex",
    urlPattern: "*://app.plex.tv/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "psa",
    name: "PSA",
    urlPattern: "*://psa.wf/movie/*, *://psa.wf/tv-show/*",
    mediaType: "auto",
    badgeSelector: "h1.post-title",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "rargb",
    name: "RARGB",
    urlPattern: "*://*.rargb.to/torrent/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "rottentomatoes",
    name: "Rotten Tomatoes",
    urlPattern: "*://*.rottentomatoes.com/m/*, *://*.rottentomatoes.com/tv/*",
    mediaType: "auto",
    badgeSelector: 'rt-text[slot="title"], h1',
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tmdb",
    name: "TMDB",
    urlPattern: "*://*.themoviedb.org/movie/*, *://*.themoviedb.org/tv/*",
    mediaType: "auto",
    badgeSelector: "section.inner_content h2 a, section.inner_content h2, .title h2 a, .title h2, h2 a",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "trakt",
    name: "Trakt",
    urlPattern: "*://*.trakt.tv/movies/*, *://*.trakt.tv/shows/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "trakt-app",
    name: "Trakt App",
    urlPattern: "*://app.trakt.tv/movies/*, *://app.trakt.tv/shows/*",
    mediaType: "auto",
    badgeSelector: "h1.short-title, h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tvdb",
    name: "TVDB",
    urlPattern: "*://*.thetvdb.com/series/*, *://*.thetvdb.com/movies/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tvmaze",
    name: "TVMaze",
    urlPattern: "*://*.tvmaze.com/shows/*, *://tvmaze.com/shows/*",
    mediaType: "show",
    badgeSelector: "header.columns h1, h1",
    isBuiltin: true,
    enabled: true,
  },
];
