import type { SiteDefinition } from "./types";

export const DEFAULT_SITES: SiteDefinition[] = [
  {
    id: "tmdb-movie",
    name: "TMDB Movies",
    urlPattern: "*://*.themoviedb.org/movie/*",
    mediaType: "movie",
    badgeSelector: "section.inner_content h2 a, section.inner_content h2, .title h2 a, .title h2, h2 a",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tmdb-tv",
    name: "TMDB TV Shows",
    urlPattern: "*://*.themoviedb.org/tv/*",
    mediaType: "show",
    badgeSelector: "section.inner_content h2 a, section.inner_content h2, .title h2 a, .title h2, h2 a",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "imdb",
    name: "IMDb",
    urlPattern: "*://*.imdb.com/title/*",
    mediaType: "auto",
    badgeSelector: 'h1[data-testid="hero-title-block__title"], h1',
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tvdb",
    name: "TVDB",
    urlPattern: "*://*.thetvdb.com/series/*",
    mediaType: "show",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "nzbgeek",
    name: "NZBGeek",
    urlPattern: "*://*.nzbgeek.info/geekseek.php*",
    mediaType: "auto",
    badgeSelector: "span.overlay_title",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "rargb",
    name: "RARGB",
    urlPattern: "*://*.rargb.to/torrent/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "psa",
    name: "PSA",
    urlPattern: "*://psa.wf/movie/*, *://psa.wf/tv-show/*",
    mediaType: "auto",
    badgeSelector: "h1.post-title",
    isBuiltin: true,
    enabled: true,
  },
];
