import type { SiteDefinition } from "./types";

export const DEFAULT_SITES: SiteDefinition[] = [
  {
    id: "tmdb-movie",
    name: "TMDB Movies",
    urlPattern: "*://*.themoviedb.org/movie/*",
    mediaType: "movie",
    badgeSelector: "section.inner_content h2 a, section.inner_content h2, .title h2 a, .title h2, h2 a",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tmdb-tv",
    name: "TMDB TV Shows",
    urlPattern: "*://*.themoviedb.org/tv/*",
    mediaType: "show",
    badgeSelector: "section.inner_content h2 a, section.inner_content h2, .title h2 a, .title h2, h2 a",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "imdb",
    name: "IMDb",
    urlPattern: "*://*.imdb.com/title/*",
    mediaType: "auto",
    badgeSelector: 'h1[data-testid="hero-title-block__title"], h1',
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tvdb-series",
    name: "TVDB Series",
    urlPattern: "*://*.thetvdb.com/series/*",
    mediaType: "show",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "tvdb-movies",
    name: "TVDB Movies",
    urlPattern: "*://*.thetvdb.com/movies/*",
    mediaType: "movie",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "nzbgeek",
    name: "NZBGeek",
    urlPattern: "*://*.nzbgeek.info/geekseek.php*",
    mediaType: "auto",
    badgeSelector: "span.overlay_title",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "rargb",
    name: "RARGB",
    urlPattern: "*://*.rargb.to/torrent/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "psa",
    name: "PSA",
    urlPattern: "*://psa.wf/movie/*, *://psa.wf/tv-show/*",
    mediaType: "auto",
    badgeSelector: "h1.post-title",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "letterboxd",
    name: "Letterboxd",
    urlPattern: "*://*.letterboxd.com/film/*",
    mediaType: "movie",
    badgeSelector: ".headline-1, h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "trakt",
    name: "Trakt",
    urlPattern: "*://*.trakt.tv/movies/*, *://*.trakt.tv/shows/*",
    mediaType: "auto",
    badgeSelector: "h1",
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "rottentomatoes",
    name: "Rotten Tomatoes",
    urlPattern: "*://*.rottentomatoes.com/m/*, *://*.rottentomatoes.com/tv/*",
    mediaType: "auto",
    badgeSelector: 'slot[name="title"], h1',
    isBuiltin: true,
    enabled: true,
  },
  {
    id: "justwatch",
    name: "JustWatch",
    urlPattern: "*://*.justwatch.com/*/movie/*, *://*.justwatch.com/*/tv-show/*",
    mediaType: "auto",
    badgeSelector: ".title-block h1, h1",
    isBuiltin: true,
    enabled: true,
  },
];
